openapi: 3.0.3
info:
  title: Rekindle Animation API
  description: API contracts for image-to-video animation feature
  version: 1.0.0

paths:
  /api/v1/jobs/{job_id}/animate:
    post:
      summary: Create animation from restored image
      description: |
        Initiates animation generation using Replicate's wan-2.5-i2v model.
        Returns immediately with pending status; completion notified via webhook.
      operationId: createAnimation
      tags:
        - Animation
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Job ID containing the source image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimationRequest'
            examples:
              basic:
                summary: Basic animation request
                value:
                  restore_id: "550e8400-e29b-41d4-a716-446655440000"
                  params:
                    prompt: "A gentle breeze moves through the scene"
                    resolution: "720p"
              high_quality:
                summary: High quality 1080p
                value:
                  restore_id: "550e8400-e29b-41d4-a716-446655440000"
                  params:
                    prompt: "The subject smiles warmly"
                    resolution: "1080p"
      responses:
        '200':
          description: Animation job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimationResponse'
        '400':
          description: Invalid request (missing prompt, invalid resolution)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '402':
          description: Insufficient credits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Job does not belong to current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Job or restore attempt not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /api/v1/webhooks/replicate/animation/{animation_id}:
    post:
      summary: Replicate animation webhook callback
      description: |
        Receives completion notification from Replicate API.
        Downloads generated video and updates animation record.
      operationId: replicateAnimationWebhook
      tags:
        - Webhooks
      parameters:
        - name: animation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Animation attempt ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplicateWebhookPayload'
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        '404':
          description: Animation attempt not found
        '500':
          description: Error processing webhook

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token

  schemas:
    AnimationRequest:
      type: object
      required:
        - params
      properties:
        restore_id:
          type: string
          format: uuid
          nullable: true
          description: Source restored image ID (uses original if null)
        model:
          type: string
          default: "replicate_wan"
          description: Animation model identifier
        params:
          type: object
          required:
            - prompt
          properties:
            prompt:
              type: string
              minLength: 1
              maxLength: 500
              description: Text prompt describing desired animation
              example: "A gentle breeze moves through the scene"
            resolution:
              type: string
              enum: ["480p", "720p", "1080p"]
              default: "720p"
              description: Output video resolution

    AnimationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Animation attempt ID
        job_id:
          type: string
          format: uuid
          description: Parent job ID
        restore_id:
          type: string
          format: uuid
          nullable: true
          description: Source restore attempt ID
        preview_s3_key:
          type: string
          description: S3 key for video ("pending" while processing)
          example: "pending"
        result_s3_key:
          type: string
          nullable: true
          description: S3 key for HD result video
        thumb_s3_key:
          type: string
          nullable: true
          description: S3 key for video thumbnail
        model:
          type: string
          nullable: true
          description: Model identifier
          example: "replicate_wan"
        params:
          type: object
          nullable: true
          description: Animation parameters
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        preview_url:
          type: string
          format: uri
          nullable: true
          description: Presigned URL for video (null while pending)
        result_url:
          type: string
          format: uri
          nullable: true
          description: Presigned URL for HD result
        thumb_url:
          type: string
          format: uri
          nullable: true
          description: Presigned URL for thumbnail

    ReplicateWebhookPayload:
      type: object
      description: Replicate prediction completion webhook payload
      properties:
        id:
          type: string
          description: Replicate prediction ID
        status:
          type: string
          enum: ["starting", "processing", "succeeded", "failed", "canceled"]
          description: Prediction status
        output:
          oneOf:
            - type: string
              format: uri
              description: Video URL (on success)
            - type: "null"
          description: Output video URL or null
        error:
          type: string
          nullable: true
          description: Error message if failed
        metrics:
          type: object
          properties:
            predict_time:
              type: number
              description: Prediction time in seconds

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
          example: "Job not found"
