'use client';

import Link from 'next/link';

const lastUpdated = 'November 13, 2025';

const sections = [
  {
    title: '1. Overview',
    content: [
      'Rekindle helps you restore, enhance, and preserve photographs using AI-assisted workflows. This Privacy Policy explains how we collect, use, store, and share personal information when you interact with our applications, including cross-device uploads, biometric authentication, and backend services powered by Supabase.',
      'By using Rekindle, you consent to the practices described here. If you do not agree, please discontinue use of the service.',
    ],
  },
  {
    title: '2. Information We Collect',
    subsections: [
      {
        heading: 'Account Information',
        bullets: [
          'Email address and password (managed by Supabase Auth).',
          'Display name, profile photo, and optional metadata (e.g., accepted terms, onboarding preferences).',
          'OAuth profile data (Google) where you choose social sign-in.',
        ],
      },
      {
        heading: 'Content You Provide',
        bullets: [
          'Photos and related metadata you upload for restoration, including derived assets generated by Rekindle.',
          'Annotations, ratings, or feedback about processing jobs.',
        ],
      },
      {
        heading: 'Usage Data',
        bullets: [
          'Log data such as IP address, device details, actions taken in-app, and timestamps for job execution.',
          'Session activity for cross-device tokens, QR codes, and biometric authentications.',
          'Rate-limiting and security events (e.g., failed login attempts) for fraud prevention.',
        ],
      },
      {
        heading: 'Payment Information',
        bullets: [
          'We outsource payment processing to a PCI-compliant provider (e.g., Stripe). Billing details submitted during credit purchases or subscription upgrades are handled directly by that provider.',
        ],
      },
    ],
  },
  {
    title: '3. How We Use Information',
    bullets: [
      'Authenticate users, maintain sessions, and protect accounts (including password resets and cross-device verification).',
      'Process and deliver restoration jobs, enhancements, and other features you request.',
      'Store and organize uploaded and processed assets within user-specific namespaces.',
      'Send service updates, onboarding messages, and transactional emails (e.g., confirmation, password reset).',
      'Monitor performance, troubleshoot issues, and improve Rekindle features.',
      'Enforce our Terms of Use and comply with legal obligations.',
    ],
  },
  {
    title: '4. How We Share Information',
    bullets: [
      'Service providers: We rely on Supabase (authentication, database, storage), cloud infrastructure partners, and analytics tools to deliver Rekindle. Each provider is contractually bound to use data only for the services we request.',
      'Legal requirements: We may disclose information if required by law, subpoena, or to protect the rights, property, or safety of Rekindle, our users, or others.',
      'Business transfers: If Rekindle is involved in a merger, acquisition, or asset sale, we may transfer user data as part of that transaction with notice where required.',
    ],
  },
  {
    title: '5. Data Retention & Deletion',
    bullets: [
      'We retain account data and stored assets for as long as your account remains active or as needed to provide Rekindle. You can request deletion through account settings; deletions enter a 30-day grace period before permanent removal.',
      'Derived assets are deleted alongside original uploads when the account is purged.',
      'We may retain certain logs or non-identifiable usage data for security, compliance, or analytics even after account deletion.',
    ],
  },
  {
    title: '6. Security',
    content: [
      'We implement technical and organizational safeguards such as TLS, Supabase Row Level Security, per-user storage prefixes, and audit logging of authentication events. However, no system is completely secure, and we cannot guarantee absolute security.',
      'You are responsible for maintaining strong passwords, safeguarding biometric devices, and revoking sessions if you suspect misuse.',
    ],
  },
  {
    title: '7. International Data Transfers',
    content: [
      'Rekindle’s infrastructure may process data in the United States or other jurisdictions depending on Supabase regions and CDN endpoints. By using the service, you consent to the transfer of information to countries that may have different data protection laws than your own.',
    ],
  },
  {
    title: '8. Your Choices & Rights',
    bullets: [
      'Access & Update: Review or update profile information via the settings page.',
      'Download: Use the data export feature to obtain a JSON archive of your content and activity.',
      'Delete: Request account deletion to remove stored content after the 30-day grace period.',
      'Email Preferences: Control marketing or product emails (where applicable) via in-email unsubscribe links or by contacting support.',
      'Legal Rights: Depending on your jurisdiction, you may have additional rights (e.g., GDPR, CCPA). Contact us to exercise those rights.',
    ],
  },
  {
    title: '9. Children\'s Privacy',
    content: [
      'Rekindle is not intended for children under 16. We do not knowingly collect personal information from children. If you believe a child has provided personal data, contact us so we can delete it.',
    ],
  },
  {
    title: '10. Changes to This Policy',
    content: [
      'We may update this Privacy Policy periodically. Material changes will be communicated via email or in-app notification. The “Last updated” date reflects the most recent version. Continued use after changes signifies acceptance.',
    ],
  },
  {
    title: '11. Contact Us',
    content: [
      'Questions or concerns about privacy? Email us at privacy@rekindle.app or write to Rekindle Privacy, 432 Memory Lane, Portland, OR 97205, USA.',
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white shadow-xl rounded-2xl p-8 sm:p-12 space-y-12">
        <header className="space-y-4">
          <span className="inline-flex items-center rounded-full bg-emerald-100 px-3 py-1 text-sm font-medium text-emerald-700">
            Privacy
          </span>
          <h1 className="text-3xl font-bold text-gray-900">Rekindle Privacy Policy</h1>
          <p className="text-sm text-gray-500">Last updated: {lastUpdated}</p>
          <p className="text-gray-600">
            We respect the trust you place in Rekindle when you share your photographs and memories. This policy explains
            how we collect, protect, and use your information.
          </p>
        </header>

        <section className="space-y-10">
          {sections.map((section) => (
            <article key={section.title} className="space-y-4">
              <h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
              {'content' in section && section.content && (
                <div className="space-y-3 text-gray-700 leading-relaxed">
                  {section.content.map((paragraph) => (
                    <p key={paragraph}>{paragraph}</p>
                  ))}
                </div>
              )}
              {'bullets' in section && section.bullets && (
                <ul className="list-disc pl-5 space-y-2 text-gray-700">
                  {section.bullets.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              )}
              {'subsections' in section && section.subsections && (
                <div className="space-y-6">
                  {section.subsections.map((subsection) => (
                    <div key={subsection.heading} className="space-y-2">
                      <h3 className="text-lg font-medium text-gray-900">{subsection.heading}</h3>
                      <ul className="list-disc pl-5 space-y-2 text-gray-700">
                        {subsection.bullets.map((bullet) => (
                          <li key={bullet}>{bullet}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              )}
            </article>
          ))}
        </section>

        <footer className="space-y-3 text-gray-600">
          <p>
            This Privacy Policy should be read together with our{' '}
            <Link href="/terms" className="text-blue-600 hover:text-blue-700 font-medium">
              Terms of Use
            </Link>
            .
          </p>
          <p>
            For additional questions or to exercise privacy rights,{' '}
            <a href="mailto:privacy@rekindle.app" className="text-blue-600 hover:text-blue-700 font-medium">
              contact us by email
            </a>{' '}
            or write to Rekindle Privacy, 432 Memory Lane, Portland, OR 97205, USA.
          </p>
        </footer>
      </div>
    </div>
  );
}



